// 4.2 Autogenerated Getters and Setters

class Book{
  String title
}

Book book = new Book()
book.setTitle("Groovy Recipes")

println book.getTitle()
// ===> Groovy Recipes


class Book{
  String title
  String author
  Integer pages

  String getTitle(){
    return title.toUpperCase()
  }
}
